# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W-tjEHIKRrEfz3plPsKlSkDYVdyDiWy8
"""

pip install opencv python

from google.colab.patches import cv2_imshow
import cv2
rasm1=cv2.imread("photo_2023-11-06_20-19-53.jpg")
cv2_imshow(rasm1)

oqqora=cv2.cvtColor(rasm1,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm2=cv2.imread("2.jpg")
cv2_imshow(rasm2)

oqqora=cv2.cvtColor(rasm2,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm3=cv2.imread("3.jpg")
cv2_imshow(rasm3)

oqqora=cv2.cvtColor(rasm3,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm4=cv2.imread("4.JPG")
cv2_imshow(rasm4)

oqqora=cv2.cvtColor(rasm4,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm5=cv2.imread("200006200985_452905.jpg")
cv2_imshow(rasm5)

oqqora=cv2.cvtColor(rasm5,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)